### ISSUE TITLE
No issue -  just saying thanks

### ISSUE THREAD

**Issue by rgfx** [GabrielDuarteM/webplayer-hotkeys#1]
I guess a star enough, but I just want to say thank you personally.  There is extension Streamkeys, but I feel it has too many options, probably slowing down my computer. Github should make review section and features suggestion section.

Speaking of which, I find myself always skipping 30 seconds at a time into a track on SoundCloud. It would be really cool to have a hotkey for that :)

we could do something like this. 

```
var e = new jQuery.Event("click");
  e.pageX = 10;
  e.pageY = 10;
  $(<canvas>).trigger(e);
```
Thanks again.

**Comment by GabeDuarteM** [comment]
Hey @rgfx, thank you very much for your feedback!

I'm going to take that into consideration when writing new features for it.

Also, I don't know if you found the extension through github or chrome's webstore, but note that the extension is published and you can download it at [Chrome WebStore](https://chrome.google.com/webstore/detail/webplayer-hotkeys/ikmkicnmahfdilneilgibeppbnolgkaf). That way, you can stay always up-to-date when a new release drops in.
