### ISSUE TITLE
Spotify play/pause hotkey not working

### ISSUE THREAD

**Issue by sterrier** [GabrielDuarteM/webplayer-hotkeys#102]
# Issue

- [x] I have searched the [issues](https://github.com/GabrielDuarteM/webplayer-hotkeys/issues) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech               | Version |
| ------------------ | ------- |
| Browser            |    Chrome 79.0.3945.88    |
| Operational System |   Windows 10  1909    |
| Extension version  |   1.3.1      |

## Problem description:

Play hotkey does not play/pause in spotify. However it opens a spotify tab if one is not already opened.

## Suggested solution:

I think the play button class might have changed. What I found in src/background.ts looks different from the html play button: class="control-button spoticon-play-16 control-button--circled".

**Comment by GabeDuarteM** [comment]
Thanks @sterrier for reporting this issue. Indeed it looks like spotify changed their classes, so I made a fix to the extension and it should be released soon!

**Comment by sterrier** [comment]
Thank you for the fix!
Would it be possible to add an option (toggle button) to disable the
opening of a spotify tab when a hotkey is pressed (happens if the tab is
not opened)?
Best,
Stéphane
