### ISSUE TITLE
Is it possible to assign only one key?

### ISSUE THREAD

**Issue by mreduar** [GabrielDuarteM/webplayer-hotkeys#134]
I'm trying to assign the multimedia keys on my keyboard and I can't. Is there a way to do it?
Also, if it is not possible, I would like to assign a single key instead of a combination... Why is it not possible to do this?

**Comment by GabeDuarteM** [comment]
Hi 👋 

That part is actually managed by Chrome, and they put some limitations on what keys you can set, for security reasons I believe. You can read more about that on [their documentation](https://developer.chrome.com/apps/commands), but according to it, the keys that they accept are: 

> Supported keys: A-Z, 0-9, Comma, Period, Home, End, PageUp, PageDown, Space, Insert,
Delete, Arrow keys (Up, Down, Left, Right) and the Media Keys (MediaNextTrack, MediaPlayPause, MediaPrevTrack, MediaStop).

> Note: All key combinations must include either Ctrl* or Alt. Combinations that involve Ctrl+Alt are not permitted in order to avoid conflicts with the AltGr key. Shift can be used in addition to Alt or Ctrl, but is not required. Modifiers (such as Ctrl) can not be used in combination with the Media Keys. Tab key was removed from list of supported keys in Chrome version 33 and above for accessibility reasons.

So to answer your question, Media Keys should be supported, but not single key shortcuts. I tried it on my end, and it seems normal, as you can see from the screenshot below:

![image](https://user-images.githubusercontent.com/7675500/77350813-5c77a900-6d3d-11ea-8715-5f89f8e450b5.png)

It would be helpful if you could properly fill the bug template including anything more you might find relevant, as it gives me more info to work with and would help me narrow down and maybe reproduce the error...

**Comment by mreduar** [comment]
Thank you for your quick and excellent response.
I figured the limitation was on Chrome's part. However, I'll show you what he requested below.

| Tech               | Version |
| ------------------ | ------- |
| Browser            |Google Chrome  Versión 77.0.3865.120 (Build official) (64 bits)|
| Operational System |  Windows 10 Enterprise LTSC   |
| Extension version  |    1.3.2    |
|Keyboard| Delux K9020 USB Wired Gaming|

## What you did:
Try assigning a media key on my keyboard.

## What happened:
When I want to assign the key to "Previous music" and press my multimedia key (arrow pointing to the left side) it is like pressing the back of the browser, and I'm going to the previous page which is the extensions page

## Problem description:
I think this more than one problem with the extension is a problem with Google Chrome that conflicts with keys already assigned by default

## Suggested solution:
It would be great if we could assign keys with an interface of the same extension in this way perhaps we could avoid this type of conflict.

**Comment by GabeDuarteM** [comment]
Thank you for providing me with the template! 

At first, I understood that you were trying to assign the music-related media keys to it (previous track, play/pause, next track, etc), but it seems now that what you are trying to assign is the key used to go back in the browser history (previous/next page), is that right?
If that's the case, then that's not one of the supported keys by chrome so, unfortunately, I'm afraid there's not much I can do on the extension side :/

What I could suggest though, as a workaround, is that if you don't use those keys you could try overriding them using something like [AutoHotkey](https://www.autohotkey.com/). Then you can assign it to either the previous track key, or another shortcut, and use that instead on the extension.

**Comment by GabeDuarteM** [comment]
Hi @MrEduar 
Just wanted to follow up with this issue and check if I can close it, considering my message above

**Comment by mreduar** [comment]
It happens that when I press the previous track key on my keyboard it's like pressing the "back" button on the browser. I don't know why this happens, I guess because Chrome associates it automatically. So when I associate this key with its extension I can't because I go to the previous page.

But well, no problem, I'll keep using the old reliable one. The mouse to control the players.

Thank you very much for your help and attention.
